---
name: TheBuildWorkflow

on:
  push:
    branches:
    - "feature/*"
    - "fix/*"
    - "hotfix/*"
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"

    - name: Do the build
      working-directory: ${{ github.repository }}
      run: |
        ls -al

    - name: get tags
      run: |
        URL=https://api.github.com/repos/${{ github.repository }}/tags
        echo $URL
        echo ${{ secrets.GITHUB_TOKEN }}
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" $URL

...
