---
name: BuildAndTest

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"

    - name: Do the build
      working-directory: ${{ github.repository }}
      run: |
        ls -al

    - name: get tags
      run: |
        sudo apt update
        sudo apt install -yqq curl
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/tags/protection

...
