---
name: BuildAndTest

on:
  workflow_call:
    inputs:
      repository-path:
        required: true
        type: string
    #secrets:
    #  token:
    #    required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"

    - name: Do the build
      working-directory: ${{ github.repository }}
      run: |
        ls -al
        # exit 1

    - name: get tags
      run: |
        URL=https://api.github.com/repos/${{ github.repository }}/tags
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" $URL

...
