---
name: TheBuildWorkflow

on:
  push:
    branches:
    - "feature/*"
    - "fix/*"
    - "hotfix/*"
    - master
    - main
  #pull_request:
  #  types:
  #  - closed
  #  branches:
  #  # some older repositories still use master, all newer ones use main
  #  - master
  #  - main
  schedule:
  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"

    - name: Do the build
      working-directory: ${{ github.repository }}
      run: |
        ls -al
...
