---
name: ScheduledWorkflow

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  call-workflow:
    uses: ${{ github.repository }}/.github/workflows/build_and_test.yml@main
    with:
      repository-path: ${{ github.repository }}
    secrets: inherit

...
